### ISSUE TITLE
Sync 12th block

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#107]
Here it is: https://ropsten.etherscan.io/tx/0xb1a07ebc3568e770ff809d91c1831c0936dce6941cf104c37fd443f3dcce897b

There are several CC (contract creation) Tx's like https://ropsten.etherscan.io/address/0xBC1FFC1620DA1468624A596CB841D35E6B2F1FB6 in it.

sync gist (not the latest version btw, ask @vyorkin if you need it too): https://gist.github.com/vyorkin/24b15a8c4bd37452414b06280fa19d45

Related discussion in gitter: [October 13, 2017 11:56 PM](https://gitter.im/exthereum/exthereum?at=59e1288ae44c43700a2d8f90)

related issues: #108

**Comment by germsvel** [comment]
@masonforest do you know what this is about? Is this true anymore?

**Comment by masonforest** [comment]
Syncing with Ropsten still fails:

````
10:26:35.309 [info]  Verified Block 0

10:26:35.400 [info]  Verified Block 1

10:26:35.513 [info]  Verified Block 2

10:26:35.592 [info]  Verified Block 3

10:26:35.681 [info]  Verified Block 4

10:26:35.762 [info]  Verified Block 5

10:26:35.870 [info]  Verified Block 6

10:26:35.989 [info]  Verified Block 7

10:26:36.093 [info]  Verified Block 8

10:26:36.199 [info]  Verified Block 9

10:26:36.287 [info]  Verified Block 10

10:26:36.501 [info]  Failed to Verify Block 11

10:26:36.505 [error] [:gas_used_mismatch, :state_root_mismatch]
````

Let's close this for now. I think it's more important for us to sync the main chain. We can re-open this or create a new issue once we have the main chain syncing.
