### ISSUE TITLE
Implement last 4 precompiled contracts

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#113]
Note that we should activate the last 4 precompiled contracts after `activateAt` block number.
My suggestion is to implement smth like the `is_active` function in the `BuiltIn` module.
It should read the corresponding precompiled account config to see if it is enabled or not. By "read" I mean to look up the `Chain.accounts` by the address of precompiled contract account to get the `activateAt` block number.

Should be done after #108

**Comment by ayrat555** [comment]
Resolved
