### ISSUE TITLE
Remove exleveldb from umbrella

### ISSUE THREAD

**Issue by germsvel** [poanetwork/mana#16]
`exleveldb` should not be in the `mana` umbrella. There is a [commit](https://github.com/exthereum/eleveldb/commit/a2203ee3a0e362b018495365ef7c3e6e0d2d1220) in `exthereum/exleveldb` fork that we want to include, so perhaps we use that as a dependency first and once that is merged upstream, we can then just use `exleveldb` from hex.

**Comment by cernivec** [comment]
https://github.com/poanetwork/mana/pull/19
