### ISSUE TITLE
Logo proposal for MANA

### ISSUE THREAD

**Issue by ggabogarcia** [poanetwork/mana#234]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by igorbarinov** [comment]
Hi @ggabogarcia 
we already have some logo assets for Mana. Thank you for the offer tho.

![2018-07-10 09 24 53](https://user-images.githubusercontent.com/424628/42498507-a4d52b4c-842c-11e8-8bde-54bb54444706.jpg)

![2018-07-10 09 25 03](https://user-images.githubusercontent.com/424628/42498481-9466833c-842c-11e8-941e-1915b56f776a.jpg)

**Comment by ggabogarcia** [comment]
The proposals are great! :) thank you so much for your time :)
