### ISSUE TITLE
Use rust library for `libsecp256k1` signature functions

### ISSUE THREAD

**Issue by masonforest** [poanetwork/mana#257]
We can use: https://github.com/hansihe/rustler to bridge to Rust

and the [parity fork](https://github.com/paritytech/rust-secp256k1) of the `secp256k1` rust crate.

**Comment by igorbarinov** [comment]
it also uses C code.
```
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1", rev = "6370d63adf4e8c91e2eae9225eef4b4e0294c5d0" }
```
