### ISSUE TITLE
Add rocksdb backend, perform simple benchmarking

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#32]
Should be faster, maybe.
see:
https://github.com/urbint/rox

**Comment by igorbarinov** [comment]
Great issue!

Recently go-ethereum had problems with leveldb with 1TB db crash https://github.com/ethereum/go-ethereum/pull/16630

Means, that we will deal with > 1TB DB for Mainnet with traces

**Comment by vyorkin** [comment]
Done, but blocked by the #48

**Comment by vyorkin** [comment]
As I've discovered lately we aren't using any DB at all yet:
https://github.com/poanetwork/mana/blob/master/apps/ex_wire/lib/ex_wire.ex#L22

I'll address this in a separate RP.
