### ISSUE TITLE
Comments reference equation numbers but not version of yellow paper

### ISSUE THREAD

**Issue by germsvel** [poanetwork/mana#41]
There are several comments in the code base that reference an equation in the yellow paper. For example, `apps/blockchain/lib/blochain/block.ex` has a comment, 

```elixir
# The following checks Holistic Validity, as defined in Eq. (29)
```

Those comments are very helpful, but they don't mention which version of the yellow paper they reference. For example, the `EIP-150 REVISION` found in [yellowpaper.io](http://yellowpaper.io/) has the holistic validity equation defined as equation 29. But the `BYZANTIUM VERSION f72032b - 2018-05-04` found in https://ethereum.github.io/yellowpaper/paper.pdf has that equation as equation 31.

**Comment by vyorkin** [comment]
@ayrat555 We could just mention the correct version of Yellow Paper for now (where? in README? is `EIP-150 REVISION` the correct one?).
But eventually, we need to update every reference to the latest version of YP.

**Comment by germsvel** [comment]
Yeah, maybe for now we just mention the version that the equations are referencing in the README (I'm not sure which one that is). In the future, it'd be nice to figure out a way to programmatically reference the correct equation. It'd be great if we could avoid having to update the comments every time a new version of the paper comes out.

**Comment by ayrat555** [comment]
I don't think there are `versions` of the paper. it just updates. so I think updating equations is a good opportunity to refresh knowledge of the yellow paper and its correspondence to programming code.

**Comment by vyorkin** [comment]
I want to do this (I've just finished re-reading the YP), would help me understand more

**Comment by ayrat555** [comment]
done
