### ISSUE TITLE
fix alias order credo check

### ISSUE THREAD

**Issue by ayrat555** [poanetwork/mana#414]
Currently, [AliasOrder](https://github.com/rrrene/credo/blob/7137277ded288e95475931ae59ea91c7032419eb/lib/credo/check/readability/alias_order.ex#L1) credo check is disabled, we should turn on this credo and fix all warnings

**Comment by germsvel** [comment]
@ayrat555 I think this is good to close, right?

**Comment by ayrat555** [comment]
yes, thanks @germsvel
