### ISSUE TITLE
Ensure the correct EVM configuration is selected based on the chain and block number

### ISSUE THREAD

**Issue by masonforest** [poanetwork/mana#461]
Currently if we run `sync_with_infura` against the Ropsten chain we fail at [block #11](https://ropsten.etherscan.io/block/11).

If you look at the debug trace of [this transaction](https://ropsten.etherscan.io/vmtrace?txhash=0xa28142d727fe9c0f86d26023cc26f3a80c89d3860c36fb98d66ce5a0bd7a706d) in the block you can see that the SELFDESTRUCT cost 5000 gas. This wasn't the case until after the homestead fork. I think the issue was that Ropsten was launched _after_ the homestead fork. It looks like this is configured [here](https://github.com/poanetwork/mana/blob/master/chains/ropsten.json#L33) but it doesn't look like we're checking that value anywhere.

We should check that and related values when verifying blocks to make sure that the right evm configuration is used.

**Comment by germsvel** [comment]
@masonforest is this done or do we still need to do this?

**Comment by masonforest** [comment]
This was fixed in #462. Thanks for being on top of this!
