### ISSUE TITLE
Use property-based testing, where appropriate

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#54]
In MMPT, ExRPL
https://github.com/whatyouhide/stream_data
https://elixir-lang.org/blog/2017/10/31/stream-data-property-based-testing-and-data-generation-for-elixir/

**Comment by ayrat555** [comment]
@vyorkin https://github.com/exthereum/ex_rlp

**Comment by vyorkin** [comment]
sure, just forked :)
