### ISSUE TITLE
Reclaim old tries from the DB

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#69]
When an account is deleted, the corresponding `storage_trie_root` is deleted also.
The problem is that the underlying DB may still keep all stored items.
We need to remove the `storage_trie_root` from the DB.

![image](https://user-images.githubusercontent.com/988849/40174055-8b077d3e-59dc-11e8-9c26-a821742bb66f.png)

related in Parity: https://github.com/paritytech/parity/blob/master/ethcore/src/executive.rs#L644

See https://github.com/poanetwork/mana/blob/master/apps/blockchain/lib/blockchain/interface/account_interface.ex#L238
and  `del_account` fn in `Account` module

**Comment by vyorkin** [comment]
yep, I've just proved it with the following test:
```elixir
  test "cleans up storage when account is deleted" do
    db = MerklePatriciaTree.Test.random_ets_db()
    address = <<0x01::160>>

    account = %Account{
      nonce: 0,
      balance: 0,
      code_hash: Keccak.kec(<<>>),
      storage_root: Trie.empty_trie_root_hash()
    }

    state =
      Trie.new(db)
      |> Account.put_account(address, account)
      |> Account.put_storage(address, 42, 24)

    account = Account.get_account(state, address)

    Account.del_account(state, address)

    dump_account_storage(db, account)

    key = 42 |> :binary.encode_unsigned() |> BitHelper.pad(32) |> Keccak.kec()
    value = Trie.new(db, account.storage_root) |> Trie.get(key)

    assert value == :not_found
  end
```

**Comment by ayrat555** [comment]
@vyorkin nice job. bug is critical in my opinion

**Comment by vyorkin** [comment]
I just can't find the place where it is being cleared in Parity or pythereum or cpp-ethereum 😕

**Comment by vyorkin** [comment]
![image](https://user-images.githubusercontent.com/988849/40207340-b1b10cc4-5a3c-11e8-8bd2-38d802324ca7.png)

So, as I can see this is exactly how it currently works, it just stores every `(k, v)` in the underlying database. But when we use the MMPT as an account storage we definitely should clear everything related to the account being deleted.

**Comment by vyorkin** [comment]
I've how they do it in parity: https://github.com/paritytech/parity/blob/a04c5b180a821c709b0ea24c7d4f21c9c2511839/util/patricia_trie/src/triedbmut.rs#L300

**Comment by vyorkin** [comment]
created #82 to track the original issue

**Comment by vyorkin** [comment]
I don't see an easy way of doing this currently, we can't just delete the old "cached" tries on every MMPT update because it can be for example update of a child block trie state_root that was derived from the parent state of a root block. I mean:

![image](https://user-images.githubusercontent.com/988849/40278706-d27451ce-5c3e-11e8-9fd7-247c655609d9.png)
