### ISSUE TITLE
Point Yellowpaper link to the version on Github

### ISSUE THREAD

**Issue by cernivec** [poanetwork/mana#70]
The Yellowpaper link  in Blockchain readme is currently pointing to: http://yellowpaper.io/

Point to https://ethereum.github.io/yellowpaper/paper.pdf with the latest version.

**Comment by germsvel** [comment]
@cernivec does this conflict with the notion in https://github.com/poanetwork/mana/issues/41?

**Comment by vyorkin** [comment]
I can update the README as part of #41 if you don't mind, as I'm currently fixing the references while reviewing the blockchain app
