### ISSUE TITLE
Handle builtin/precompiled contract accounts

### ISSUE THREAD

**Issue by vyorkin** [poanetwork/mana#76]
See Appendix E. in the YP:

![image](https://user-images.githubusercontent.com/988849/40082086-9ba558f4-5898-11e8-9c25-3e691f7ab8fd.png)

https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json#L2900
https://github.com/poanetwork/mana/blob/master/apps/blockchain/lib/blockchain/chain.ex#L65

**Comment by vyorkin** [comment]
see `EVM.Builtin` also

**Comment by vyorkin** [comment]
Related: https://vitalik.ca/general/2017/09/14/prehistory.html
How its implemented in Parity: https://github.com/paritytech/parity/blob/master/ethcore/src/builtin.rs

**Comment by cernivec** [comment]
@masonforest what is the `s0` in this case `ExthCrypto.Hash.hash(s0, ExthCrypto.Hash.kec)`?

**Comment by masonforest** [comment]
Conversation in slack: https://poanetwork.slack.com/archives/GA89BNBT7/p1526561179000117

**Comment by cernivec** [comment]
This needs refactoring and adding more tests.

**Comment by ayrat555** [comment]
done
